name: rust_to_dart_bincode_converter
description: Converts Rust structs to Dart Classes implementing BincodeEncodable and toString with an empty constructor.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  recase: ^4.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
